services:
  dash-app:
    build: .            # <--- ESTA LÍNEA ES LA QUE FALTA
    image: kdashboard   # Ahora esto servirá como etiqueta local
    container_name: kdash_container
    ports:
      - "8051:8051"
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
    networks:
      - shared_network

networks:
  shared_network:
    external: true