services:
  dash-app:
    image: kdashboard
    ports:
      - "8051:8051"
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
    networks:
      - shared_network # Just the name here

# This top-level section tells Compose the network already exists
networks:
  shared_network:
    external: true